# Linear algebra

In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.4'

## Matrix and vector products

Q1. Predict the results of the following code.

In [5]:
x = [1, 2]
y = [[4, 1], [2, 2]]
print(np.dot(x, y))
print(np.dot(y, x))
print(np.matmul(x, y))
print(np.inner(x, y))
print(np.inner(y, x))

[8 5]
[6 6]
[8 5]
[6 6]
[6 6]


Q2. Predict the results of the following code.

In [6]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
print(np.dot(y, x))
print(np.matmul(y, x))

[[4 1]
 [2 2]
 [1 1]]
[[4 1]
 [2 2]
 [1 1]]


Q3. Predict the results of the following code.

In [7]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
print(np.vdot(x, y))
print(np.vdot(y, x))
print(np.dot(x.flatten(), y.flatten()))
print(np.inner(x.flatten(), y.flatten()))
print((x*y).sum())

30
30
30
30
30


Q4. Predict the results of the following code.

In [8]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
print(np.inner(x, y))
print(np.inner(y, x))
print(np.outer(x, y))
print(np.outer(y, x))

abb
abb
[['a' 'aa']
 ['b' 'bb']]
[['a' 'b']
 ['aa' 'bb']]


## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [9]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
np.linalg.cholesky(x)

array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8.,  5.,  3.]])

Q6. Compute the qr factorization of x and verify it.

In [10]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
np.linalg.qr(x)

(array([[-0.85714287,  0.3942857 ,  0.33142856],
        [-0.42857143, -0.9028571 , -0.03428571],
        [ 0.2857143 , -0.17142858,  0.94285715]], dtype=float32),
 array([[ -14.,  -21.,   14.],
        [   0., -175.,   70.],
        [   0.,    0.,  -35.]], dtype=float32))

Q7. Factor x by Singular Value Decomposition and verify it.

In [11]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
np.linalg.svd(x)

(array([[ 0.,  1.,  0.,  0.],
        [ 1.,  0.,  0.,  0.],
        [ 0.,  0.,  0., -1.],
        [ 0.,  0.,  1.,  0.]], dtype=float32),
 array([3.      , 2.236068, 2.      , 0.      ], dtype=float32),
 array([[-0.       ,  0.       ,  1.       , -0.       ,  0.       ],
        [ 0.4472136, -0.       , -0.       , -0.       ,  0.8944272],
        [-0.       ,  1.       ,  0.       , -0.       ,  0.       ],
        [ 0.       ,  0.       ,  0.       ,  1.       ,  0.       ],
        [-0.8944272,  0.       ,  0.       ,  0.       ,  0.4472136]],
       dtype=float32))

## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [15]:
x = np.diag((1, 2, 3))
e_val, e_vec = np.linalg.eig(x)
e_val, e_vec

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

Q9. Predict the results of the following code.

In [16]:
print(np.array_equal(np.dot(x, e_vec), e_val * e_vec))

True


## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [21]:
x = np.arange(1, 10).reshape((3, 3))
norm_fro = np.linalg.norm(x, ord='fro')
cond_fro = np.linalg.cond(x, p='fro')
print(norm_fro, cond_fro, sep='\n', end='')

16.881943016134134
4.561770736605098e+17

Q11. Calculate the determinant of x.

In [22]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.det(x)

-2.0000000000000004

Q12. Calculate the rank of x.

In [23]:
x = np.eye(4)
np.linalg.matrix_rank(x)

4

Q13. Compute the sign and natural logarithm of the determinant of x.

In [24]:
x = np.arange(1, 5).reshape((2, 2))
np.linalg.slogdet(x)

(-1.0, 0.6931471805599455)

Q14. Return the sum along the diagonal of x.

In [25]:
x = np.eye(4)
np.trace(x)

4.0

## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [26]:
x = np.array([[1., 2.], [3., 4.]])
np.linalg.inv(x)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])